site_name: Token Nexus Platform Documentation
site_description: Comprehensive documentation for the Token Nexus Platform - A modern blockchain application platform with secure app runtime framework
site_author: Token Nexus Team
site_url: https://your-username.github.io/token-nexus-platform

# Repository
repo_name: token-nexus-platform
repo_url: https://github.com/your-username/token-nexus-platform
edit_uri: edit/main/docsite/

# Copyright
copyright: Copyright &copy; 2025 Token Nexus Platform

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ?
          'dark' : 'light'

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/token-nexus-platform
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/your-username/token-nexus-platform
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-username

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: your-username
      repo: token-nexus-platform
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: 
    - Overview: index.md
    - Project Summary: PROJECT_SUMMARY.md
    - Getting Started: README.md
  
  - Architecture:
    - Overview: architecture/README.md
    - Controllers: architecture/controllers.md
  
  - Features:
    - Overview: features/README.md
    - Authentication: features/authentication.md
    - Dashboard: features/dashboard.md
    - App Marketplace: features/app-marketplace.md
    - App Runtime Framework: features/app-runtime-framework.md
  
  - Implementation:
    - Progress: implementation/README.md
  
  - Technical:
    - Overview: technical/README.md
    - App Runtime API: technical/app-runtime-api.md
  
  - Tasks:
    - Task Management: tasks/README.md
